services:
  apisix:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
  imgproxy:
    image: darthsim/imgproxy:v3.24
    environment:
      IMGPROXY_WATERMARK_URL: http://server:3000/apache-apisix.avif
  server:
    build: .
